package tokenize

import (
	v1beta2 "cloud.google.com/go/language/apiv1beta2/languagepb"
)

type (
	DependencyEdgeLabel int32
	DependencyEdge      struct {
		HeadTokenIndex int32
		Label          DependencyEdgeLabel
	}
)

const (
	DependencyEdgeLabelUnknown      = DependencyEdgeLabel(v1beta2.DependencyEdge_UNKNOWN)
	DependencyEdgeLabelAbbrev       = DependencyEdgeLabel(v1beta2.DependencyEdge_ABBREV)
	DependencyEdgeLabelAComp        = DependencyEdgeLabel(v1beta2.DependencyEdge_ACOMP)
	DependencyEdgeLabelAdvCl        = DependencyEdgeLabel(v1beta2.DependencyEdge_ADVCL)
	DependencyEdgeLabelAdvMod       = DependencyEdgeLabel(v1beta2.DependencyEdge_ADVMOD)
	DependencyEdgeLabelAMod         = DependencyEdgeLabel(v1beta2.DependencyEdge_AMOD)
	DependencyEdgeLabelAppos        = DependencyEdgeLabel(v1beta2.DependencyEdge_APPOS)
	DependencyEdgeLabelAttr         = DependencyEdgeLabel(v1beta2.DependencyEdge_ATTR)
	DependencyEdgeLabelAux          = DependencyEdgeLabel(v1beta2.DependencyEdge_AUX)
	DependencyEdgeLabelAuxPass      = DependencyEdgeLabel(v1beta2.DependencyEdge_AUXPASS)
	DependencyEdgeLabelCC           = DependencyEdgeLabel(v1beta2.DependencyEdge_CC)
	DependencyEdgeLabelCComp        = DependencyEdgeLabel(v1beta2.DependencyEdge_CCOMP)
	DependencyEdgeLabelConj         = DependencyEdgeLabel(v1beta2.DependencyEdge_CONJ)
	DependencyEdgeLabelCSubj        = DependencyEdgeLabel(v1beta2.DependencyEdge_CSUBJ)
	DependencyEdgeLabelCSubjPass    = DependencyEdgeLabel(v1beta2.DependencyEdge_CSUBJPASS)
	DependencyEdgeLabelDep          = DependencyEdgeLabel(v1beta2.DependencyEdge_DEP)
	DependencyEdgeLabelDet          = DependencyEdgeLabel(v1beta2.DependencyEdge_DET)
	DependencyEdgeLabelDiscourse    = DependencyEdgeLabel(v1beta2.DependencyEdge_DISCOURSE)
	DependencyEdgeLabelDObj         = DependencyEdgeLabel(v1beta2.DependencyEdge_DOBJ)
	DependencyEdgeLabelExpl         = DependencyEdgeLabel(v1beta2.DependencyEdge_EXPL)
	DependencyEdgeLabelGoesWith     = DependencyEdgeLabel(v1beta2.DependencyEdge_GOESWITH)
	DependencyEdgeLabelIObj         = DependencyEdgeLabel(v1beta2.DependencyEdge_IOBJ)
	DependencyEdgeLabelMark         = DependencyEdgeLabel(v1beta2.DependencyEdge_MARK)
	DependencyEdgeLabelMwE          = DependencyEdgeLabel(v1beta2.DependencyEdge_MWE)
	DependencyEdgeLabelMwV          = DependencyEdgeLabel(v1beta2.DependencyEdge_MWV)
	DependencyEdgeLabelNeg          = DependencyEdgeLabel(v1beta2.DependencyEdge_NEG)
	DependencyEdgeLabelNN           = DependencyEdgeLabel(v1beta2.DependencyEdge_NN)
	DependencyEdgeLabelNPAdvMod     = DependencyEdgeLabel(v1beta2.DependencyEdge_NPADVMOD)
	DependencyEdgeLabelNSubj        = DependencyEdgeLabel(v1beta2.DependencyEdge_NSUBJ)
	DependencyEdgeLabelNSubjPass    = DependencyEdgeLabel(v1beta2.DependencyEdge_NSUBJPASS)
	DependencyEdgeLabelNum          = DependencyEdgeLabel(v1beta2.DependencyEdge_NUM)
	DependencyEdgeLabelNumber       = DependencyEdgeLabel(v1beta2.DependencyEdge_NUMBER)
	DependencyEdgeLabelP            = DependencyEdgeLabel(v1beta2.DependencyEdge_P)
	DependencyEdgeLabelParataxis    = DependencyEdgeLabel(v1beta2.DependencyEdge_PARATAXIS)
	DependencyEdgeLabelPartMod      = DependencyEdgeLabel(v1beta2.DependencyEdge_PARTMOD)
	DependencyEdgeLabelPComp        = DependencyEdgeLabel(v1beta2.DependencyEdge_PCOMP)
	DependencyEdgeLabelPObj         = DependencyEdgeLabel(v1beta2.DependencyEdge_POBJ)
	DependencyEdgeLabelPoss         = DependencyEdgeLabel(v1beta2.DependencyEdge_POSS)
	DependencyEdgeLabelPostNeg      = DependencyEdgeLabel(v1beta2.DependencyEdge_POSTNEG)
	DependencyEdgeLabelPreComp      = DependencyEdgeLabel(v1beta2.DependencyEdge_PRECOMP)
	DependencyEdgeLabelPreConj      = DependencyEdgeLabel(v1beta2.DependencyEdge_PRECONJ)
	DependencyEdgeLabelPreDet       = DependencyEdgeLabel(v1beta2.DependencyEdge_PREDET)
	DependencyEdgeLabelPref         = DependencyEdgeLabel(v1beta2.DependencyEdge_PREF)
	DependencyEdgeLabelPrep         = DependencyEdgeLabel(v1beta2.DependencyEdge_PREP)
	DependencyEdgeLabelPRonl        = DependencyEdgeLabel(v1beta2.DependencyEdge_PRONL)
	DependencyEdgeLabelPrt          = DependencyEdgeLabel(v1beta2.DependencyEdge_PRT)
	DependencyEdgeLabelPS           = DependencyEdgeLabel(v1beta2.DependencyEdge_PS)
	DependencyEdgeLabelQuantMod     = DependencyEdgeLabel(v1beta2.DependencyEdge_QUANTMOD)
	DependencyEdgeLabelRCMod        = DependencyEdgeLabel(v1beta2.DependencyEdge_RCMOD)
	DependencyEdgeLabelRCModRel     = DependencyEdgeLabel(v1beta2.DependencyEdge_RCMODREL)
	DependencyEdgeLabelRDropP       = DependencyEdgeLabel(v1beta2.DependencyEdge_RDROP)
	DependencyEdgeLabelRef          = DependencyEdgeLabel(v1beta2.DependencyEdge_REF)
	DependencyEdgeLabelRemnant      = DependencyEdgeLabel(v1beta2.DependencyEdge_REMNANT)
	DependencyEdgeLabelReparandum   = DependencyEdgeLabel(v1beta2.DependencyEdge_REPARANDUM)
	DependencyEdgeLabelRoot         = DependencyEdgeLabel(v1beta2.DependencyEdge_ROOT)
	DependencyEdgeLabelSNum         = DependencyEdgeLabel(v1beta2.DependencyEdge_SNUM)
	DependencyEdgeLabelSuff         = DependencyEdgeLabel(v1beta2.DependencyEdge_SUFF)
	DependencyEdgeLabelTMod         = DependencyEdgeLabel(v1beta2.DependencyEdge_TMOD)
	DependencyEdgeLabelTopic        = DependencyEdgeLabel(v1beta2.DependencyEdge_TOPIC)
	DependencyEdgeLabelVMod         = DependencyEdgeLabel(v1beta2.DependencyEdge_VMOD)
	DependencyEdgeLabelVocative     = DependencyEdgeLabel(v1beta2.DependencyEdge_VOCATIVE)
	DependencyEdgeLabelXComp        = DependencyEdgeLabel(v1beta2.DependencyEdge_XCOMP)
	DependencyEdgeLabelSuffix       = DependencyEdgeLabel(v1beta2.DependencyEdge_SUFFIX)
	DependencyEdgeLabelTitle        = DependencyEdgeLabel(v1beta2.DependencyEdge_TITLE)
	DependencyEdgeLabelAdvPhMod     = DependencyEdgeLabel(v1beta2.DependencyEdge_ADVPHMOD)
	DependencyEdgeLabelAuxCaus      = DependencyEdgeLabel(v1beta2.DependencyEdge_AUXCAUS)
	DependencyEdgeLabelAuxVV        = DependencyEdgeLabel(v1beta2.DependencyEdge_AUXVV)
	DependencyEdgeLabelDtMod        = DependencyEdgeLabel(v1beta2.DependencyEdge_DTMOD)
	DependencyEdgeLabelForeign      = DependencyEdgeLabel(v1beta2.DependencyEdge_FOREIGN)
	DependencyEdgeLabelKw           = DependencyEdgeLabel(v1beta2.DependencyEdge_KW)
	DependencyEdgeLabelList         = DependencyEdgeLabel(v1beta2.DependencyEdge_LIST)
	DependencyEdgeLabelNomC         = DependencyEdgeLabel(v1beta2.DependencyEdge_NOMC)
	DependencyEdgeLabelNomCSubj     = DependencyEdgeLabel(v1beta2.DependencyEdge_NOMCSUBJ)
	DependencyEdgeLabelNomCSubjPass = DependencyEdgeLabel(v1beta2.DependencyEdge_NOMCSUBJPASS)
	DependencyEdgeLabelNumC         = DependencyEdgeLabel(v1beta2.DependencyEdge_NUMC)
	DependencyEdgeLabelCop          = DependencyEdgeLabel(v1beta2.DependencyEdge_COP)
	DependencyEdgeLabelDislocated   = DependencyEdgeLabel(v1beta2.DependencyEdge_DISLOCATED)
	DependencyEdgeLabelAsp          = DependencyEdgeLabel(v1beta2.DependencyEdge_ASP)
	DependencyEdgeLabelGMod         = DependencyEdgeLabel(v1beta2.DependencyEdge_GMOD)
	DependencyEdgeLabelGObj         = DependencyEdgeLabel(v1beta2.DependencyEdge_GOBJ)
	DependencyEdgeLabelInfMod       = DependencyEdgeLabel(v1beta2.DependencyEdge_INFMOD)
	DependencyEdgeLabelMes          = DependencyEdgeLabel(v1beta2.DependencyEdge_MES)
	DependencyEdgeLabelNComp        = DependencyEdgeLabel(v1beta2.DependencyEdge_NCOMP)
)
